deploy:
  provider: pypi
  user: akesterson
  password:
    secure: H0XRotyZm7xxpkR5bTxyjWSnwrUQUscKIj9Miqn9l1aROZN3GQ4oLLP8Epa590UQ/VLSlKQ28oalejlbDHG452K1726NAytO3r/0Oy/htuBf5DoR3VCa+aivOjeCVd2Axgc0385BB2ouG8aYJOL7Lc0sJ9fFUG7pQ2f3lZlzZLo=
  on:
    tags: true
    branch: master
language: python
sudo: false
env:
- TOXENV=py26
- TOXENV=py27
- TOXENV=py32
- TOXENV=py33
- TOXENV=py34
- TOXENV=pypy
install:
- travis_retry pip install tox
script:
- tox
before_install:
- openssl aes-256-cbc -K $encrypted_f0c597e60bd7_key -iv $encrypted_f0c597e60bd7_iv
  -in fixtures/pass3.json.encrypted.enc -out pass3/etc/pass3.json -d
